# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6de27aa0aa7238cf0aef5f3b025b09e53bd49ccbaaf88e3c939c74298ce1daaaf98aca444f1992f21b21b190300c4e665b6137ce2054a1076977f03fda9a10

test:
  secret_key_base: ed952ad1710f227fa4371b728fea9d509555187d228d480348860b93dfd40333e522d186c8a556e0ad6eb07f203fb5fca627810f8e7da488946f10d25b140964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
